//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuRegistrationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int id { get; set; }
        public string studentname { get; set; }
        public System.DateTime birthday { get; set; }
        public System.DateTime registereddate { get; set; }
        public int user_id { get; set; }
        public string subjectstream { get; set; }
    
        public virtual user user { get; set; }
    }

    public enum ScienceStream{
        Mathematics,
        Bioscience
    }

    public enum OtherStream
    {
        Art,
        Commerce
    }
}
